name: Go
on: [push]
jobs:

  build:
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: master
          POSTGRES_PASSWORD: masterkey
          POSTGRES_DB: trackpal
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up psql
      run: sudo apt-get install -y postgresql-client

    - name: Get dependencies
      run: |
        go mod vendor

    - name: Lint
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
        make lint

    - name: Unit Test
      run: make unit_test

    - name: Integration test
      env:
        POSTGRES_USER: master
        PGPASSWORD: masterkey
        POSTGRES_DB: trackpal
        POSTGRES_DSN: "user=master password=masterkey dbname=trackpal sslmode=disable"
      run: |
        psql -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<< $(cat migrations/*.sql)
        make integration_test

    - name: Coverage
      run: |
        make coverage_full
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./output/coverage.cov #optional
