name: Go
on: [push]
jobs:

  test:
    env:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: trackpal
      POSTGRES_DSN: "user=master password=masterkey dbname=trackpal sslmode=disable"

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
        # required since postgres container does not provide any health checks
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install tools and deps
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
        sudo apt-get install -y postgresql-client
        go mod vendor

    - name: Lint
      run: |
        $(go env GOPATH)/bin/golangci-lint run -c ./build/.golangci-lint.yml ./...

    - name: Unit Test
      run: make unit_test

    - name: Integration test
      run: |
        psql -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<< $(cat migrations/*.sql)
        make integration_test

    - name: Generate coverage report
      run: |
        make coverage_full

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./output/coverage.cov
