name: Trackpal
on: [push]
jobs:

  cicd:
    env:
      POSTGRES_USER: master
      PGPASSWORD: masterkey # required by pgsql
      POSTGRES_DB: trackpal
      POSTGRES_DSN: "user=master password=masterkey dbname=trackpal sslmode=disable"

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: master
          POSTGRES_PASSWORD: masterkey
          POSTGRES_DB: trackpal
        ports:
          - 5432:5432
        # required since postgres container does not provide any health checks
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: Test, build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install tools and deps
      run: |
        sudo apt-get update
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
        sudo apt-get install -y postgresql-client
        go mod vendor

    - name: Setup identity
      run: |
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y );
        eval $(ssh-agent -s);
        echo "${{ secrets.TRACKPAL_PEM }}" > ~/trackpal.pem;
        cat ~/trackpal.pem;

    - name: Lint
      run: |
        $(go env GOPATH)/bin/golangci-lint run -c ./build/.golangci-lint.yml ./...

    - name: Unit Test
      run: make unit_test

    - name: Integration test
      run: |
        psql -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<< $(cat migrations/*.sql)
        make integration_test

    - name: Generate coverage report
      run: |
        make coverage_full

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./output/coverage.cov

    - name: Build
      run: |
        make build

    - name: Deploy (upload server)
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        PORT: ${{ secrets.REMOTE_PORT }}
        KEY: ${{ secrets.SERVER_SSH_KEY }}
      with:
        source: "target"
        target: "trackpal"

    - name: Deploy (upload docs)
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        PORT: ${{ secrets.REMOTE_PORT }}
        KEY: ${{ secrets.SERVER_SSH_KEY }}
      with:
        source: "docs"
        target: "trackpal"

    - name: Deploy (use new version)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        PORT: ${{ secrets.REMOTE_PORT }}
        KEY: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo systemctl stop trackpal
          mv trackpal/target/trackpal trackpal/trackpal
          sudo systemctl start trackpal
